/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Fatura.Fatura;
import io.github.nicolazlxl.TesteSQLPOO.Fatura.FaturaRepository;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author taina
 */
public class CadastroNovaFatura extends javax.swing.JFrame {

    private final DefaultListModel<Fatura> modelFatura;
    private final FaturaRepository repository;
    /**
     * Creates new form CadastroNovaFatura
     */
    public CadastroNovaFatura() {
        
        repository = new FaturaRepository(); 
        
        modelFatura = new DefaultListModel<>();
        modelFatura.addAll(repository.findAll());
        initComponents();
        
        lblAlerta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroFatura = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDataFechamentoFatura = new javax.swing.JLabel();
        lblValorTotalFatura = new javax.swing.JLabel();
        lblStatusFatura = new javax.swing.JLabel();
        txtDataFechamentoFatura = new javax.swing.JTextField();
        txtValorTotalFatura = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        cmbStatusFatura = new javax.swing.JComboBox<>();
        pnlListagem = new javax.swing.JPanel();
        lblFaturas = new javax.swing.JLabel();
        scrFaturas = new javax.swing.JScrollPane();
        lstFaturas = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        bntExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        bntRestaurarLixeira = new javax.swing.JButton();
        bntExcluirLixeira = new javax.swing.JButton();
        bntEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPrincipal.setForeground(new java.awt.Color(10, 54, 158));

        pnlCadastroFatura.setBackground(new java.awt.Color(221, 221, 253));
        pnlCadastroFatura.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(10, 54, 158)));

        lblTitulo.setBackground(new java.awt.Color(10, 54, 158));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastre uma nova Fatura:");
        lblTitulo.setOpaque(true);

        lblDataFechamentoFatura.setForeground(new java.awt.Color(10, 54, 158));
        lblDataFechamentoFatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataFechamentoFatura.setText("Data de Fechamento da Fatura:");

        lblValorTotalFatura.setForeground(new java.awt.Color(10, 54, 158));
        lblValorTotalFatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTotalFatura.setText("Valor total:");

        lblStatusFatura.setForeground(new java.awt.Color(10, 54, 158));
        lblStatusFatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatusFatura.setText("Status:");

        bntSalvar.setBackground(new java.awt.Color(10, 54, 158));
        bntSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntSalvar.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        cmbStatusFatura.setForeground(new java.awt.Color(10, 54, 158));
        cmbStatusFatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em aberto", "Paga", "Cancelada" }));
        cmbStatusFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroFaturaLayout = new javax.swing.GroupLayout(pnlCadastroFatura);
        pnlCadastroFatura.setLayout(pnlCadastroFaturaLayout);
        pnlCadastroFaturaLayout.setHorizontalGroup(
            pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValorTotalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFechamentoFatura)
                            .addComponent(lblStatusFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDataFechamentoFatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtValorTotalFatura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatusFatura, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlCadastroFaturaLayout.setVerticalGroup(
            pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataFechamentoFatura, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblDataFechamentoFatura))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotalFatura)
                    .addComponent(txtValorTotalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatusFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusFatura))
                .addGap(38, 38, 38)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        tabPrincipal.addTab("Cadastro Fatura", pnlCadastroFatura);

        pnlListagem.setBackground(new java.awt.Color(221, 221, 253));
        pnlListagem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(10, 54, 158)));

        lblFaturas.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblFaturas.setForeground(new java.awt.Color(10, 54, 158));
        lblFaturas.setText("Faturas:");

        lstFaturas.setModel(modelFatura);
        scrFaturas.setViewportView(lstFaturas);

        buttonGroup1.add(radNaoExcluidos);
        radNaoExcluidos.setForeground(new java.awt.Color(10, 54, 158));
        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        buttonGroup1.add(radExcluidos);
        radExcluidos.setForeground(new java.awt.Color(10, 54, 158));
        radExcluidos.setText("Excluídos");
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        bntExcluir.setBackground(new java.awt.Color(10, 54, 158));
        bntExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLixeira.setForeground(new java.awt.Color(10, 54, 158));
        lblLixeira.setText("Lixeira:");

        bntRestaurarLixeira.setBackground(new java.awt.Color(10, 54, 158));
        bntRestaurarLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntRestaurarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntRestaurarLixeira.setText("Restaurar");
        bntRestaurarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestaurarLixeiraActionPerformed(evt);
            }
        });

        bntExcluirLixeira.setBackground(new java.awt.Color(10, 54, 158));
        bntExcluirLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntExcluirLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluirLixeira.setText("Excluir");
        bntExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirLixeiraActionPerformed(evt);
            }
        });

        bntEsvaziarLixeira.setBackground(new java.awt.Color(10, 54, 158));
        bntEsvaziarLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntEsvaziarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntEsvaziarLixeira.setText("Esvaziar");
        bntEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setBackground(new java.awt.Color(0, 153, 255));
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione uma Fatura!");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFaturas)
                    .addComponent(scrFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radNaoExcluidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLixeira)
                            .addComponent(radExcluidos)
                            .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblFaturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntRestaurarLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluirLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntEsvaziarLixeira))
                    .addComponent(scrFaturas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        
        LocalDate dataFechamento;
        
        try {
            dataFechamento = LocalDate.parse(txtDataFechamentoFatura.getText());
        if (dataFechamento.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "A data não pode ser uma data passada.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return;
        }
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Use o formato AAAA-MM-DD.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double valorTotal;
        try {
            valorTotal = Double.parseDouble(txtValorTotalFatura.getText());
            if (valorTotal <= 0) {
                JOptionPane.showMessageDialog(this, "O valor da fatura deve ser maior que zero.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O valor deve ser um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String status = (String) cmbStatusFatura.getSelectedItem(); 
        
        JOptionPane.showMessageDialog(this, "Fatura Cadastrada com Sucesso!" + "\n"
                                            + "Data de Fechamento: "+ dataFechamento + "\n" 
                                            + "Valor Total: " + valorTotal + "\n" 
                                            + "Status: " + status + "\n");
         
        Fatura f1 = new Fatura();
        
        f1.setDataFechamento(dataFechamento);
        f1.setValorTotal(valorTotal);
        f1.setStatus (status);
        
        repository.saveOrUpdate(f1);
        modelFatura.addElement(f1);
        
        txtDataFechamentoFatura.setText("");
        txtValorTotalFatura.setText("");
        cmbStatusFatura.setSelectedIndex(-1);

    }//GEN-LAST:event_bntSalvarActionPerformed

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed
        
        enableTrash(false);
        modelFatura.clear();
        modelFatura.addAll(repository.findAll());
        
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed
        
        enableTrash(true);
        modelFatura.clear();
        modelFatura.addAll(repository.findTrash());
        
    }//GEN-LAST:event_radExcluidosActionPerformed

    private void bntRestaurarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestaurarLixeiraActionPerformed
       
        if(lstFaturas.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma fatura!");
            return;
        }
     
        List<Fatura> selection = lstFaturas.getSelectedValuesList();
            
        for(Fatura aux: selection){
                
            aux.setToTrash(false);
          
            repository.saveOrUpdate(aux);
            modelFatura.removeElement(aux);  
        }
      
    }//GEN-LAST:event_bntRestaurarLixeiraActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        
        if(lstFaturas.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma fatura!");
            return;
        }
      
        List<Fatura> selection = lstFaturas.getSelectedValuesList();
            
        for(Fatura aux: selection){
                
            aux.setToTrash(true);
          
            repository.saveOrUpdate(aux);
            modelFatura.removeElement(aux);
        }
          
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirLixeiraActionPerformed

        if(lstFaturas.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma fatura!");
            return;
        }
     
        List<Fatura> selection = lstFaturas.getSelectedValuesList();
            
        for(Fatura aux: selection){
            
            repository.delete(aux);
            modelFatura.removeElement(aux);
            showWarning("Fatura Excluída!");
        }
 
    }//GEN-LAST:event_bntExcluirLixeiraActionPerformed

    private void bntEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEsvaziarLixeiraActionPerformed
        
        repository.EmptyTrash();
        modelFatura.clear();
        showWarning("Lixeira esvaziada");
        
    }//GEN-LAST:event_bntEsvaziarLixeiraActionPerformed

    private void cmbStatusFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusFaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusFaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNovaFatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsvaziarLixeira;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExcluirLixeira;
    private javax.swing.JButton bntRestaurarLixeira;
    private javax.swing.JButton bntSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbStatusFatura;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblDataFechamentoFatura;
    private javax.swing.JLabel lblFaturas;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblStatusFatura;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorTotalFatura;
    private javax.swing.JList<Fatura> lstFaturas;
    private javax.swing.JPanel pnlCadastroFatura;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrFaturas;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtDataFechamentoFatura;
    private javax.swing.JTextField txtValorTotalFatura;
    // End of variables declaration//GEN-END:variables

private void enableTrash(boolean status) {
    
        bntExcluir.setEnabled(!status);

        bntExcluirLixeira.setEnabled(status);
        bntRestaurarLixeira.setEnabled(status);
        bntEsvaziarLixeira.setEnabled(status);
    }

    private void showWarning(String warning) {
            
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
          
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
          
        timer.setRepeats(false);
        timer.start();
    }


}
