/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Fatura.Fatura;
import io.github.nicolazlxl.TesteSQLPOO.Fatura.FaturaRepository;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author taina
 */
public class CadastroNovaFatura extends javax.swing.JFrame {

    private final DefaultListModel<Fatura> modelFatura;
    private final FaturaRepository repository;
    /**
     * Creates new form CadastroNovaFatura
     */
    public CadastroNovaFatura() {
        
        repository = new FaturaRepository(); 
        
        modelFatura = new DefaultListModel<>();
        modelFatura.addAll(repository.findAll());
        initComponents();
        
        lblAlerta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroFatura = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDataFechamentoFatura = new javax.swing.JLabel();
        lblValorTotalFatura = new javax.swing.JLabel();
        lblStatusFatura = new javax.swing.JLabel();
        txtDataFechamentoFatura = new javax.swing.JTextField();
        txtValorTotalFatura = new javax.swing.JTextField();
        txtStatusFatura = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        pnlListagem = new javax.swing.JPanel();
        lblFaturas = new javax.swing.JLabel();
        scrFaturas = new javax.swing.JScrollPane();
        lstFaturas = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        bntExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        bntRestaurarLixeira = new javax.swing.JButton();
        bntExcluirLixeira = new javax.swing.JButton();
        bntEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Seja Bem-Vindo!");

        lblDataFechamentoFatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataFechamentoFatura.setText("Data de Fechamento da Fatura:");

        lblValorTotalFatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTotalFatura.setText("Valor total:");

        lblStatusFatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatusFatura.setText("Status:");

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroFaturaLayout = new javax.swing.GroupLayout(pnlCadastroFatura);
        pnlCadastroFatura.setLayout(pnlCadastroFaturaLayout);
        pnlCadastroFaturaLayout.setHorizontalGroup(
            pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValorTotalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFechamentoFatura)
                            .addComponent(lblStatusFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDataFechamentoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatusFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntSalvar)))
                    .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlCadastroFaturaLayout.setVerticalGroup(
            pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroFaturaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataFechamentoFatura)
                    .addComponent(txtDataFechamentoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotalFatura)
                    .addComponent(txtValorTotalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusFatura)
                    .addComponent(txtStatusFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(bntSalvar)
                .addGap(34, 34, 34))
        );

        tabPrincipal.addTab("Cadastro Fatura", pnlCadastroFatura);

        lblFaturas.setText("Faturas:");

        lstFaturas.setModel(modelFatura);
        scrFaturas.setViewportView(lstFaturas);

        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        radExcluidos.setText("Excluídos");
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setText("Lixeira:");

        bntRestaurarLixeira.setText("Restaurar");
        bntRestaurarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestaurarLixeiraActionPerformed(evt);
            }
        });

        bntExcluirLixeira.setText("Excluir");
        bntExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirLixeiraActionPerformed(evt);
            }
        });

        bntEsvaziarLixeira.setText("Esvaziar");
        bntEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setBackground(new java.awt.Color(255, 153, 153));
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlerta.setText("Selecione uma Fatura!");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(lblFaturas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAlerta))
                    .addComponent(scrFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radNaoExcluidos)
                    .addComponent(lblLixeira)
                    .addComponent(radExcluidos)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFaturas)
                    .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntRestaurarLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntExcluirLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntEsvaziarLixeira)
                        .addGap(18, 18, 18))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(scrFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
        LocalDate dataFechamento = LocalDate.parse(txtDataFechamentoFatura.getText());
        double valorTotal = Double.parseDouble(txtValorTotalFatura.getText());
        String status = txtStatusFatura.getText();
        
        JOptionPane.showMessageDialog(this, "Fatura Gerada!" + "\n"
                                            + "Data de Fechamento: "+ dataFechamento + "\n" 
                                            + "Valor Total: " + valorTotal + "\n" 
                                            + "Status: " + status + "\n");
         
        Fatura f1 = new Fatura();
        //FaturaRepository FRepository = new FaturaRepository();
        
        f1.setDataFechamento(dataFechamento);
        f1.setValorTotal(valorTotal);
        f1.setStatus (status);
        
        new FaturaRepository().saveOrUpdate(f1);
        //repository.saveOrUpdate(f1);
        //FRepository().saveorUpdate(f1);
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed
        
        enableTrash(false);
        modelFatura.clear();
        modelFatura.addAll(repository.findAll());
        
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed
        
        enableTrash(false);
        modelFatura.clear();
        modelFatura.addAll(repository.findTrash());
        
    }//GEN-LAST:event_radExcluidosActionPerformed

    private void bntRestaurarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestaurarLixeiraActionPerformed
       
        if(lstFaturas.getSelectedIndices().length == 0){
            return;
        }
     
            List<Fatura> selection = lstFaturas.getSelectedValuesList();
            
            for(Fatura aux: selection){
                
                aux.setToTrash(false);
          
                repository.saveOrUpdate(aux);
                modelFatura.removeElement(aux);
            }
    }//GEN-LAST:event_bntRestaurarLixeiraActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        
         if(lstFaturas.getSelectedIndices().length == 0){
            return;
        }
      
        List<Fatura> selection = lstFaturas.getSelectedValuesList();
            
        for(Fatura aux: selection){
                
            aux.setToTrash(true);
          
            repository.saveOrUpdate(aux);
            modelFatura.removeElement(aux);
         }
          
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirLixeiraActionPerformed

        if(lstFaturas.getSelectedIndices().length == 0){
            return;
        }
     
            List<Fatura> selection = lstFaturas.getSelectedValuesList();
            
            for(Fatura aux: selection){
                repository.delete(aux);
                modelFatura.removeElement(aux);
            }
    }//GEN-LAST:event_bntExcluirLixeiraActionPerformed

    private void bntEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEsvaziarLixeiraActionPerformed
        
        repository.EmptyTrash();
        modelFatura.clear();
        
    }//GEN-LAST:event_bntEsvaziarLixeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNovaFatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsvaziarLixeira;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExcluirLixeira;
    private javax.swing.JButton bntRestaurarLixeira;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblDataFechamentoFatura;
    private javax.swing.JLabel lblFaturas;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblStatusFatura;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorTotalFatura;
    private javax.swing.JList<Fatura> lstFaturas;
    private javax.swing.JPanel pnlCadastroFatura;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrFaturas;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtDataFechamentoFatura;
    private javax.swing.JTextField txtStatusFatura;
    private javax.swing.JTextField txtValorTotalFatura;
    // End of variables declaration//GEN-END:variables

private void enableTrash(boolean status) {
    
        bntExcluir.setEnabled(!status);

        bntExcluirLixeira.setEnabled(status);
        bntRestaurarLixeira.setEnabled(status);
        bntEsvaziarLixeira.setEnabled(status);
    }

}
