/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Transacao.Transacao;
import io.github.nicolazlxl.TesteSQLPOO.Transacao.TransacaoRepository;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author taina
 */
public class CadastroNovaTransacao extends javax.swing.JFrame {

    private final DefaultListModel<Transacao> modelTransacao;
    private final TransacaoRepository repository;
    /**
     * Creates new form CadastroNovaTransacao
     */
    public CadastroNovaTransacao() {
        
        repository = new TransacaoRepository();
        
        modelTransacao = new DefaultListModel<>();
        modelTransacao.addAll(repository.findAll());
        initComponents();
        
        lblAlerta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroTransacao = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTipoTransacao = new javax.swing.JLabel();
        lblValorTransacao = new javax.swing.JLabel();
        lblDataTransacao = new javax.swing.JLabel();
        lblContaOrigemTransacao = new javax.swing.JLabel();
        txtTipoTransacao = new javax.swing.JTextField();
        txtValorTransacao = new javax.swing.JTextField();
        txtDataTransacao = new javax.swing.JTextField();
        txtContaOrigemTransacao = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        lblContaDestinoTransacao = new javax.swing.JLabel();
        txtContaDestinoTransacao = new javax.swing.JTextField();
        lblFuncionario = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        pnlListagem = new javax.swing.JPanel();
        lblTransacaoes = new javax.swing.JLabel();
        scrTransacoes = new javax.swing.JScrollPane();
        lstTransacoes = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        bntExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        bntRestaurarLixeira = new javax.swing.JButton();
        bntExcluirLixeira = new javax.swing.JButton();
        bntEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Seja Bem-Vindo!");

        lblTipoTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoTransacao.setText("Tipo de Transação:");

        lblValorTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTransacao.setText("Valor:");

        lblDataTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataTransacao.setText("Data:");

        lblContaOrigemTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContaOrigemTransacao.setText("Conta de Origem:");

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        lblContaDestinoTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContaDestinoTransacao.setText("Conta de Destino:");

        lblFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFuncionario.setText("Funcionário Responsável:");

        javax.swing.GroupLayout pnlCadastroTransacaoLayout = new javax.swing.GroupLayout(pnlCadastroTransacao);
        pnlCadastroTransacao.setLayout(pnlCadastroTransacaoLayout);
        pnlCadastroTransacaoLayout.setHorizontalGroup(
            pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntSalvar)
                            .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblContaDestinoTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDataTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblValorTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTipoTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(lblContaOrigemTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContaOrigemTransacao)
                                    .addComponent(txtContaDestinoTransacao)
                                    .addComponent(txtFuncionario)
                                    .addComponent(txtTipoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorTransacao)
                                    .addComponent(txtDataTransacao)))))
                    .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblTitulo)))
                .addGap(47, 47, 47))
        );
        pnlCadastroTransacaoLayout.setVerticalGroup(
            pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoTransacao)
                    .addComponent(txtTipoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTransacao)
                    .addComponent(txtValorTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataTransacao)
                    .addComponent(txtDataTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaOrigemTransacao)
                    .addComponent(txtContaOrigemTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContaDestinoTransacao)
                    .addComponent(txtContaDestinoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(bntSalvar)
                .addContainerGap())
        );

        tabPrincipal.addTab("Cadastro Transação", pnlCadastroTransacao);

        lblTransacaoes.setText("Transações:");

        lstTransacoes.setModel(modelTransacao);
        scrTransacoes.setViewportView(lstTransacoes);

        buttonGroup1.add(radNaoExcluidos);
        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        buttonGroup1.add(radExcluidos);
        radExcluidos.setText("Excluídos");
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setText("Lixeira:");

        bntRestaurarLixeira.setText("Restaurar");
        bntRestaurarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestaurarLixeiraActionPerformed(evt);
            }
        });

        bntExcluirLixeira.setText("Excluir");
        bntExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirLixeiraActionPerformed(evt);
            }
        });

        bntEsvaziarLixeira.setText("Esvaziar");
        bntEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setBackground(new java.awt.Color(255, 102, 102));
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlerta.setText("Selecione uma Transação!");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(scrTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radNaoExcluidos)
                            .addComponent(radExcluidos)
                            .addComponent(lblLixeira)
                            .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(lblTransacaoes)
                        .addGap(41, 41, 41)
                        .addComponent(lblAlerta)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransacaoes)
                    .addComponent(lblAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrTransacoes)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluir)
                        .addGap(12, 12, 12)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntRestaurarLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluirLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntEsvaziarLixeira)))
                .addContainerGap())
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        
        String tipo = txtTipoTransacao.getText();
        double valor = Double.parseDouble(txtValorTransacao.getText());
        LocalDate data = LocalDate.parse(txtDataTransacao.getText());
        String ContaOrigem = txtContaOrigemTransacao.getText();
        String ContaDestino = txtContaDestinoTransacao.getText();
        String Funcionario = txtFuncionario.getText();
        
        Transacao t1 = new Transacao();
        
        t1.setTipo(tipo);
        t1.setValor(valor);
        t1.setData(data);
        t1.setContaOrigem(ContaOrigem);
        t1.setContaDestino(ContaDestino);
        t1.setFuncionario(Funcionario);
        
        JOptionPane.showMessageDialog(this, "Transação Concluída com Sucesso!" + "\n"
                                            + "Tipo: "+ tipo + "\n" 
                                            + "Valor: " + valor + "\n" 
                                            + "Data: " + data + "\n"
                                            + "Conta Origem: " + ContaOrigem + "\n"
                                            + "Conta Destino: " + ContaDestino + "\n"
                                            + "Funcionário Responsável:: " + Funcionario + "\n");
        
        repository.saveOrUpdate(t1);
        
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed

        enableTrash(false);
        modelTransacao.clear();
        modelTransacao.addAll(repository.findAll());
        
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed
        
        enableTrash(true);
        modelTransacao.clear();
        modelTransacao.addAll(repository.findTrash());
        
    }//GEN-LAST:event_radExcluidosActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed

        if(lstTransacoes.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma transação!");
            return;
        }
      
        List<Transacao> selection = lstTransacoes.getSelectedValuesList();
            
        for(Transacao aux: selection){
            
            aux.setToTrash(true);
          
            repository.saveOrUpdate(aux);
            modelTransacao.removeElement(aux);   
        }
            
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntRestaurarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestaurarLixeiraActionPerformed
 
        if(lstTransacoes.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma transação!");
            return;
        }
     
        List<Transacao> selection = lstTransacoes.getSelectedValuesList();
            
        for(Transacao aux: selection){
                
            aux.setToTrash(false);
          
            repository.saveOrUpdate(aux);
            modelTransacao.removeElement(aux);     
        }
            
    }//GEN-LAST:event_bntRestaurarLixeiraActionPerformed

    private void bntExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirLixeiraActionPerformed
      
        if(lstTransacoes.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma transação!");
            return;
        }
     
        List<Transacao> selection = lstTransacoes.getSelectedValuesList();
            
        for(Transacao aux: selection){
                   
            repository.delete(aux);
            modelTransacao.removeElement(aux);
            showWarning("Transação Excluída!");
        }
            
    }//GEN-LAST:event_bntExcluirLixeiraActionPerformed

    private void bntEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEsvaziarLixeiraActionPerformed
        
        repository.EmptyTrash();
        modelTransacao.clear();
        showWarning("Lixeira esvaziada");
        
    }//GEN-LAST:event_bntEsvaziarLixeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the ftabPrincipal */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNovaTransacao().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsvaziarLixeira;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExcluirLixeira;
    private javax.swing.JButton bntRestaurarLixeira;
    private javax.swing.JButton bntSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblContaDestinoTransacao;
    private javax.swing.JLabel lblContaOrigemTransacao;
    private javax.swing.JLabel lblDataTransacao;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblTipoTransacao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTransacaoes;
    private javax.swing.JLabel lblValorTransacao;
    private javax.swing.JList<Transacao> lstTransacoes;
    private javax.swing.JPanel pnlCadastroTransacao;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrTransacoes;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtContaDestinoTransacao;
    private javax.swing.JTextField txtContaOrigemTransacao;
    private javax.swing.JTextField txtDataTransacao;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtTipoTransacao;
    private javax.swing.JTextField txtValorTransacao;
    // End of variables declaration//GEN-END:variables

    private void enableTrash(boolean status) {
    
        bntExcluir.setEnabled(!status);

        bntExcluirLixeira.setEnabled(status);
        bntRestaurarLixeira.setEnabled(status);
        bntEsvaziarLixeira.setEnabled(status);
    }

    private void showWarning(String warning) {
            
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
          
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
          
        timer.setRepeats(false);
        timer.start();
    }
    
}
