/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Contrato.Contrato;
import io.github.nicolazlxl.TesteSQLPOO.Contrato.ContratoRepository;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CadastrarNovoContrato extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarNovoContrato
     */
    public CadastrarNovoContrato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastraContrato = new javax.swing.JPanel();
        lblCadastrarContrato = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDataCadastro = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtDataCadastro = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        pnlListagem = new javax.swing.JPanel();
        lblListaContratos = new javax.swing.JLabel();
        srcContrato = new javax.swing.JScrollPane();
        lstContratos = new javax.swing.JList<>();
        radPresenteBanco = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastrarContrato.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCadastrarContrato.setForeground(new java.awt.Color(0, 0, 102));
        lblCadastrarContrato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrarContrato.setText("Cadastrar Contrato");

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTotal.setText("Valor Total:");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("Status:");

        lblDataCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataCadastro.setText("Data de Cadastro:");

        btnSalvar.setBackground(new java.awt.Color(0, 0, 51));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastraContratoLayout = new javax.swing.GroupLayout(pnlCadastraContrato);
        pnlCadastraContrato.setLayout(pnlCadastraContratoLayout);
        pnlCadastraContratoLayout.setHorizontalGroup(
            pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastraContratoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblCadastrarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnlCadastraContratoLayout.createSequentialGroup()
                .addGroup(pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastraContratoLayout.createSequentialGroup()
                        .addGroup(pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDataCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus)
                            .addComponent(txtDataCadastro)))
                    .addGroup(pnlCadastraContratoLayout.createSequentialGroup()
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorTotal)))
                .addContainerGap())
            .addGroup(pnlCadastraContratoLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCadastraContratoLayout.setVerticalGroup(
            pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastraContratoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastraContratoLayout.createSequentialGroup()
                        .addComponent(lblCadastrarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastraContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Cadastrar Contrato", pnlCadastraContrato);

        lblListaContratos.setText("Lista de Contratos");

        srcContrato.setViewportView(lstContratos);

        radPresenteBanco.setText("Presente no Banco");
        radPresenteBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPresenteBancoActionPerformed(evt);
            }
        });

        radExcluidos.setText("Excluidos");

        btnExcluir.setBackground(new java.awt.Color(0, 0, 51));
        btnExcluir.setText("Excluir");

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLixeira.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLixeira.setText("Lixeira");

        btnRestaurar.setBackground(new java.awt.Color(0, 0, 51));
        btnRestaurar.setText("Restaurar");

        btnExcluirLixeira.setBackground(new java.awt.Color(0, 0, 51));
        btnExcluirLixeira.setText("Excluir");

        btnEsvaziar.setBackground(new java.awt.Color(0, 0, 51));
        btnEsvaziar.setText("Esvaziar");

        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione um Contrato");

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srcContrato)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radExcluidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radPresenteBanco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEsvaziar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblListaContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListaContratos)
                    .addComponent(lblAlerta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srcContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radPresenteBanco)
                    .addComponent(lblLixeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radExcluidos)
                    .addComponent(btnRestaurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnExcluirLixeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEsvaziar))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
           double valorTotal = Double.parseDouble(txtValorTotal.getText());
           String status = txtStatus.getText();
           LocalDate dataContrato = LocalDate.parse(txtDataCadastro.getText());
           
           Contrato ct1 = new Contrato();
           ContratoRepository ct1Repository = new ContratoRepository();
           
           ct1.setDataContrato(dataContrato);
           ct1.setStatus(status);
           ct1.setValorTotal(valorTotal);

        JOptionPane.showMessageDialog(null, "Contrato Criado:" + 
                                             "\n" + "\n"
                                            + valorTotal + "\n"
                                             + dataContrato + "\n"
                                             + status + "\n");
        
        ct1Repository.saveOrUpdate(ct1);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radPresenteBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPresenteBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radPresenteBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarNovoContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblCadastrarContrato;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblListaContratos;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JList<String> lstContratos;
    private javax.swing.JPanel pnlCadastraContrato;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radPresenteBanco;
    private javax.swing.JScrollPane srcContrato;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
