/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.CartaoCredito.CartaoCredito;
import io.github.nicolazlxl.TesteSQLPOO.CartaoCredito.CartaoCreditoRepository;

import java.util.List;


import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sarah Emanuelle e Nicolas
 */
public class CadastrarNovoCartaoCredito extends javax.swing.JFrame {

    
        

    private final DefaultListModel<CartaoCredito> modelCartao;
    private final CartaoCreditoRepository repository;
    
    
  
    /**
     * Creates new form CadastrarNovoCartãoCredito
     */
    public CadastrarNovoCartaoCredito() {
          repository = new CartaoCreditoRepository();
        
        modelCartao = new DefaultListModel<>();
        modelCartao.addAll(repository.findAll());
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastraCartao = new javax.swing.JPanel();
        lblCadastraCartaoCredito = new javax.swing.JLabel();
        lblNumeroCartao = new javax.swing.JLabel();
        lblLimiteTotalCartao = new javax.swing.JLabel();
        lblLimiteDisponivelCartao = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtNumeroCartaoCredito = new javax.swing.JTextField();
        txtLimiteTotalCartao = new javax.swing.JTextField();
        txtLimiteDisponivelCartao = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        pnlListagem = new javax.swing.JPanel();
        lblListaCartoes = new javax.swing.JLabel();
        radPresenteBanco = new javax.swing.JRadioButton();
        radExcluido = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        btnRestaurarLixeira = new javax.swing.JButton();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Cartão de Credito");

        lblCadastraCartaoCredito.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblCadastraCartaoCredito.setForeground(new java.awt.Color(102, 0, 0));
        lblCadastraCartaoCredito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastraCartaoCredito.setText("Cadastra Cartão de Credito");

        lblNumeroCartao.setText("Numero do Cartão de Crédito:");

        lblLimiteTotalCartao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLimiteTotalCartao.setText("Limite Total do Cartão:");

        lblLimiteDisponivelCartao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLimiteDisponivelCartao.setText("Limite Disponivel do Cartão:");

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("Status:");

        txtNumeroCartaoCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCartaoCreditoActionPerformed(evt);
            }
        });

        txtLimiteTotalCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteTotalCartaoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(102, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setActionCommand("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastraCartaoLayout = new javax.swing.GroupLayout(pnlCadastraCartao);
        pnlCadastraCartao.setLayout(pnlCadastraCartaoLayout);
        pnlCadastraCartaoLayout.setHorizontalGroup(
            pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastraCartaoLayout.createSequentialGroup()
                .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastraCartaoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblCadastraCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(pnlCadastraCartaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLimiteDisponivelCartao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLimiteTotalCartao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumeroCartao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroCartaoCredito)
                            .addComponent(txtLimiteTotalCartao)
                            .addComponent(txtLimiteDisponivelCartao)
                            .addComponent(txtStatus)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastraCartaoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalvar)))))
                .addContainerGap())
        );
        pnlCadastraCartaoLayout.setVerticalGroup(
            pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastraCartaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastraCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCartaoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteTotalCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimiteTotalCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteDisponivelCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimiteDisponivelCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastraCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Cadastra Cartão de Credito", pnlCadastraCartao);

        lblListaCartoes.setText("Lista de Cartões de Credito");

        buttonGroup1.add(radPresenteBanco);
        radPresenteBanco.setText("Presente no Banco");
        radPresenteBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPresenteBancoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radExcluido);
        radExcluido.setText("Excluidos");
        radExcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidoActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(51, 0, 0));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLixeira.setText("Lixeira");

        btnRestaurarLixeira.setBackground(new java.awt.Color(51, 0, 0));
        btnRestaurarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurarLixeira.setText("Restaurar");
        btnRestaurarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarLixeiraActionPerformed(evt);
            }
        });

        btnExcluirLixeira.setBackground(new java.awt.Color(51, 0, 0));
        btnExcluirLixeira.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirLixeira.setText("Apagar");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnEsvaziarLixeira.setBackground(new java.awt.Color(51, 0, 0));
        btnEsvaziarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        btnEsvaziarLixeira.setText("Esvaziar");
        btnEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione um Cartão de Credito");

        jList1.setModel(modelCartao);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaCartoes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radExcluido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radPresenteBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRestaurarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addComponent(lblLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnEsvaziarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaCartoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radPresenteBanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurarLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirLixeira))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEsvaziarLixeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblAlerta)
                .addContainerGap())
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCartaoCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCartaoCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCartaoCreditoActionPerformed

    private void txtLimiteTotalCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteTotalCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimiteTotalCartaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String numero = txtNumeroCartaoCredito.getText();
        double limiteTotal = Double.parseDouble(txtLimiteTotalCartao.getText());
        double limiteDisponivel = Double.parseDouble(txtLimiteDisponivelCartao.getText());
        String status = txtStatus.getText();
        
        CartaoCredito c1 = new CartaoCredito();
        CartaoCreditoRepository CRepository = new CartaoCreditoRepository();
        
        c1.setNumero(numero);
        c1.setLimiteDisponivel(limiteDisponivel);
        c1.setLimiteTotal(limiteTotal);
        c1.setStatus(status);
        
        
        JOptionPane.showMessageDialog(null, "Criamos um novo Cartão de Credito para você!"+ 
                                            numero + "\n" + 
                                            limiteTotal + "\n" + 
                                            limiteDisponivel + "\n" +  
                                            status + "\n");
        
        CRepository.saveOrUpdate(c1);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radPresenteBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPresenteBancoActionPerformed
        // TODO add your handling code here:
           enableTrash(false);
           modelCartao.clear();
           modelCartao.addAll(repository.findAll());
    }//GEN-LAST:event_radPresenteBancoActionPerformed

    private void radExcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidoActionPerformed
        // TODO add your handling code here:
           enableTrash(true);
          modelCartao.clear();
          modelCartao.addAll(repository.findTrash());
    }//GEN-LAST:event_radExcluidoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
           if(jList1.getSelectedIndices().length == 0){
            //showWarning("Selecione ao menos uma agência");
            return;
        }
      
            List<CartaoCredito> selection = jList1.getSelectedValuesList();
            
            for(CartaoCredito aux: selection){
                
                aux.setToTrash(true);
          
                    repository.saveOrUpdate(aux);
                    modelCartao.removeElement(aux);
            }
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRestaurarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarLixeiraActionPerformed
        // TODO add your handling code here:
        
           if(jList1.getSelectedIndices().length == 0){
            //showWarning("Selecione ao menos uma agência");
            return;
        }
      
            List<CartaoCredito> selection = jList1.getSelectedValuesList();
            
            for(CartaoCredito aux: selection){
                
                aux.setToTrash(false);
          
                    repository.saveOrUpdate(aux);
                    modelCartao.removeElement(aux);
            }
      
        
    }//GEN-LAST:event_btnRestaurarLixeiraActionPerformed

    private void btnEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarLixeiraActionPerformed
        // TODO add your handling code here:
        
         repository.EmptyTrash();
          modelCartao.clear();
    }//GEN-LAST:event_btnEsvaziarLixeiraActionPerformed

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
        // TODO add your handling code here:
        
           if(jList1.getSelectedIndices().length == 0){
            //showWarning("Selecione ao menos uma agência");
            return;
        }
      
            List<CartaoCredito> selection = jList1.getSelectedValuesList();
            
            for(CartaoCredito aux: selection){
                
                aux.setToTrash(false);
          
                    repository.delete(aux);
                    modelCartao.removeElement(aux);
            }
        
        
    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoCartaoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoCartaoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoCartaoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoCartaoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarNovoCartaoCredito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziarLixeira;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurarLixeira;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<CartaoCredito> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblCadastraCartaoCredito;
    private javax.swing.JLabel lblLimiteDisponivelCartao;
    private javax.swing.JLabel lblLimiteTotalCartao;
    private javax.swing.JLabel lblListaCartoes;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblNumeroCartao;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlCadastraCartao;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluido;
    private javax.swing.JRadioButton radPresenteBanco;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtLimiteDisponivelCartao;
    private javax.swing.JTextField txtLimiteTotalCartao;
    private javax.swing.JTextField txtNumeroCartaoCredito;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
private void enableTrash(boolean status) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       
        btnExcluir.setEnabled(!status);

        btnEsvaziarLixeira.setEnabled(status);
        btnExcluirLixeira.setEnabled(status);
        btnRestaurarLixeira.setEnabled(status);
    }
}

