/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Transacao.Transacao;
import io.github.nicolazlxl.TesteSQLPOO.Transacao.TransacaoRepository;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author taina
 */
public class CadastroNovaTransacao extends javax.swing.JFrame {

    private final DefaultListModel<Transacao> modelTransacao;
    private final TransacaoRepository repository;
    /**
     * Creates new form CadastroNovaTransacao
     */
    public CadastroNovaTransacao() {
        
        repository = new TransacaoRepository();
        
        modelTransacao = new DefaultListModel<>();
        modelTransacao.addAll(repository.findAll());
        initComponents();
        
        lblAlerta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroTransacao = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTipoTransacao = new javax.swing.JLabel();
        lblValorTransacao = new javax.swing.JLabel();
        lblDataTransacao = new javax.swing.JLabel();
        lblContaOrigemTransacao = new javax.swing.JLabel();
        txtValorTransacao = new javax.swing.JTextField();
        txtDataTransacao = new javax.swing.JTextField();
        txtContaOrigemTransacao = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        lblContaDestinoTransacao = new javax.swing.JLabel();
        txtContaDestinoTransacao = new javax.swing.JTextField();
        lblFuncionario = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        cmbTipoTransacao = new javax.swing.JComboBox<>();
        pnlListagem = new javax.swing.JPanel();
        lblTransacaoes = new javax.swing.JLabel();
        scrTransacoes = new javax.swing.JScrollPane();
        lstTransacoes = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        bntExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        bntRestaurarLixeira = new javax.swing.JButton();
        bntExcluirLixeira = new javax.swing.JButton();
        bntEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPrincipal.setBackground(new java.awt.Color(240, 211, 255));
        tabPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        tabPrincipal.setForeground(new java.awt.Color(102, 0, 102));

        pnlCadastroTransacao.setBackground(new java.awt.Color(240, 211, 255));
        pnlCadastroTransacao.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));

        lblTitulo.setBackground(new java.awt.Color(102, 0, 102));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Faça uma nova Transação:");
        lblTitulo.setOpaque(true);

        lblTipoTransacao.setForeground(new java.awt.Color(102, 0, 102));
        lblTipoTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoTransacao.setText("Tipo de Transação:");

        lblValorTransacao.setForeground(new java.awt.Color(102, 0, 102));
        lblValorTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTransacao.setText("Valor:");

        lblDataTransacao.setForeground(new java.awt.Color(102, 0, 102));
        lblDataTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataTransacao.setText("Data:");

        lblContaOrigemTransacao.setForeground(new java.awt.Color(102, 0, 102));
        lblContaOrigemTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContaOrigemTransacao.setText("Conta de Origem:");

        bntSalvar.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntSalvar.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        lblContaDestinoTransacao.setForeground(new java.awt.Color(102, 0, 102));
        lblContaDestinoTransacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblContaDestinoTransacao.setText("Conta de Destino:");

        lblFuncionario.setForeground(new java.awt.Color(102, 0, 102));
        lblFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFuncionario.setText("Funcionário Responsável:");

        cmbTipoTransacao.setForeground(new java.awt.Color(102, 0, 102));
        cmbTipoTransacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIX", "TED", "DOC" }));

        javax.swing.GroupLayout pnlCadastroTransacaoLayout = new javax.swing.GroupLayout(pnlCadastroTransacao);
        pnlCadastroTransacao.setLayout(pnlCadastroTransacaoLayout);
        pnlCadastroTransacaoLayout.setHorizontalGroup(
            pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroTransacaoLayout.createSequentialGroup()
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblContaDestinoTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDataTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValorTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTipoTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(lblContaOrigemTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblFuncionario))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContaOrigemTransacao)
                            .addComponent(txtContaDestinoTransacao)
                            .addComponent(txtFuncionario)
                            .addComponent(txtValorTransacao)
                            .addComponent(txtDataTransacao)
                            .addComponent(cmbTipoTransacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
            .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlCadastroTransacaoLayout.setVerticalGroup(
            pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroTransacaoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoTransacao)
                    .addComponent(cmbTipoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTransacao)
                    .addComponent(txtValorTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataTransacao))
                .addGap(21, 21, 21)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaOrigemTransacao)
                    .addComponent(txtContaOrigemTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContaDestinoTransacao)
                    .addComponent(txtContaDestinoTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pnlCadastroTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tabPrincipal.addTab("Cadastro Transação", pnlCadastroTransacao);

        pnlListagem.setBackground(new java.awt.Color(240, 211, 255));

        lblTransacaoes.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTransacaoes.setForeground(new java.awt.Color(102, 0, 102));
        lblTransacaoes.setText("Transações:");

        lstTransacoes.setModel(modelTransacao);
        scrTransacoes.setViewportView(lstTransacoes);

        buttonGroup1.add(radNaoExcluidos);
        radNaoExcluidos.setForeground(new java.awt.Color(102, 0, 102));
        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        buttonGroup1.add(radExcluidos);
        radExcluidos.setForeground(new java.awt.Color(102, 0, 102));
        radExcluidos.setText("Excluídos");
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        bntExcluir.setBackground(new java.awt.Color(102, 0, 102));
        bntExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLixeira.setForeground(new java.awt.Color(102, 0, 102));
        lblLixeira.setText("Lixeira:");

        bntRestaurarLixeira.setBackground(new java.awt.Color(102, 0, 102));
        bntRestaurarLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntRestaurarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntRestaurarLixeira.setText("Restaurar");
        bntRestaurarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestaurarLixeiraActionPerformed(evt);
            }
        });

        bntExcluirLixeira.setBackground(new java.awt.Color(102, 0, 102));
        bntExcluirLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntExcluirLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluirLixeira.setText("Excluir");
        bntExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirLixeiraActionPerformed(evt);
            }
        });

        bntEsvaziarLixeira.setBackground(new java.awt.Color(102, 0, 102));
        bntEsvaziarLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntEsvaziarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntEsvaziarLixeira.setText("Esvaziar");
        bntEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setBackground(new java.awt.Color(204, 0, 255));
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione uma Transação!");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransacaoes)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addComponent(scrTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radNaoExcluidos)
                            .addComponent(radExcluidos)
                            .addComponent(lblLixeira)
                            .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTransacaoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntRestaurarLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluirLixeira)
                        .addGap(18, 18, 18)
                        .addComponent(bntEsvaziarLixeira)
                        .addGap(35, 35, 35))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(scrTransacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed

        
        String tipo = (String) cmbTipoTransacao.getSelectedItem();
        
        double valor;
        try {
            valor = Double.parseDouble(txtValorTransacao.getText());
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, "O valor da transação deve ser maior que zero.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O valor deve ser um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LocalDate data;
        
        try {
            data = LocalDate.parse(txtDataTransacao.getText());
            if (data.isBefore(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "A data não pode ser uma data passada.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Use o formato AAAA-MM-DD.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String ContaOrigem = txtContaOrigemTransacao.getText();
        
        if (ContaOrigem.length() != 5) {
            JOptionPane.showMessageDialog(this, "O número da conta deve ter 5 caracteres.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String ContaDestino = txtContaDestinoTransacao.getText();
        
        if (ContaDestino.length() != 5) {
            JOptionPane.showMessageDialog(this, "O número da conta deve ter 5 caracteres.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        String Funcionario = txtFuncionario.getText();
        
        Transacao t1 = new Transacao();
        
        t1.setTipo(tipo);
        t1.setValor(valor);
        t1.setData(data);
        t1.setContaOrigem(ContaOrigem);
        t1.setContaDestino(ContaDestino);
        t1.setFuncionario(Funcionario);
        
        JOptionPane.showMessageDialog(this, "Transação Concluída com Sucesso!" + "\n"
                                            + "Tipo: "+ tipo + "\n" 
                                            + "Valor: " + valor + "\n" 
                                            + "Data: " + data + "\n"
                                            + "Conta Origem: " + ContaOrigem + "\n"
                                            + "Conta Destino: " + ContaDestino + "\n"
                                            + "Funcionário Responsável:: " + Funcionario + "\n");
        
        repository.saveOrUpdate(t1);
        modelTransacao.addElement(t1);
        
        cmbTipoTransacao.setSelectedIndex(-1);
        txtValorTransacao.setText("");
        txtDataTransacao.setText("");
        txtContaOrigemTransacao.setText("");
        txtContaDestinoTransacao.setText("");
        txtFuncionario.setText("");
        
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed

        enableTrash(false);
        modelTransacao.clear();
        modelTransacao.addAll(repository.findAll());
        
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed
        
        enableTrash(true);
        modelTransacao.clear();
        modelTransacao.addAll(repository.findTrash());
        
    }//GEN-LAST:event_radExcluidosActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed

        if(lstTransacoes.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma transação!");
            return;
        }
      
        List<Transacao> selection = lstTransacoes.getSelectedValuesList();
            
        for(Transacao aux: selection){
            
            aux.setToTrash(true);
          
            repository.saveOrUpdate(aux);
            modelTransacao.removeElement(aux);   
        }
            
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntRestaurarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestaurarLixeiraActionPerformed
 
        if(lstTransacoes.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma transação!");
            return;
        }
     
        List<Transacao> selection = lstTransacoes.getSelectedValuesList();
            
        for(Transacao aux: selection){
                
            aux.setToTrash(false);
          
            repository.saveOrUpdate(aux);
            modelTransacao.removeElement(aux);     
        }
            
    }//GEN-LAST:event_bntRestaurarLixeiraActionPerformed

    private void bntExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirLixeiraActionPerformed
      
        if(lstTransacoes.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma transação!");
            return;
        }
     
        List<Transacao> selection = lstTransacoes.getSelectedValuesList();
            
        for(Transacao aux: selection){
                   
            repository.delete(aux);
            modelTransacao.removeElement(aux);
            showWarning("Transação Excluída!");
        }
            
    }//GEN-LAST:event_bntExcluirLixeiraActionPerformed

    private void bntEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEsvaziarLixeiraActionPerformed
        
        repository.EmptyTrash();
        modelTransacao.clear();
        showWarning("Lixeira esvaziada");
        
    }//GEN-LAST:event_bntEsvaziarLixeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the ftabPrincipal */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNovaTransacao().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsvaziarLixeira;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExcluirLixeira;
    private javax.swing.JButton bntRestaurarLixeira;
    private javax.swing.JButton bntSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbTipoTransacao;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblContaDestinoTransacao;
    private javax.swing.JLabel lblContaOrigemTransacao;
    private javax.swing.JLabel lblDataTransacao;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblTipoTransacao;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTransacaoes;
    private javax.swing.JLabel lblValorTransacao;
    private javax.swing.JList<Transacao> lstTransacoes;
    private javax.swing.JPanel pnlCadastroTransacao;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrTransacoes;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtContaDestinoTransacao;
    private javax.swing.JTextField txtContaOrigemTransacao;
    private javax.swing.JTextField txtDataTransacao;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtValorTransacao;
    // End of variables declaration//GEN-END:variables

    private void enableTrash(boolean status) {
    
        bntExcluir.setEnabled(!status);

        bntExcluirLixeira.setEnabled(status);
        bntRestaurarLixeira.setEnabled(status);
        bntEsvaziarLixeira.setEnabled(status);
    }

    private void showWarning(String warning) {
            
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
          
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
          
        timer.setRepeats(false);
        timer.start();
    }
    
}
