/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Conta.Conta;
import io.github.nicolazlxl.TesteSQLPOO.Conta.ContaRepository;
import javax.swing.JOptionPane;
import java.time.LocalDate;

/**
 *
 * @author taina
 */
public class CadastroNovaConta extends javax.swing.JFrame {

    /**
     * Creates new form CadastroNovaConta
     */
    public CadastroNovaConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroConta = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        lblLimiteDiarioSaque = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtDataCriacao = new javax.swing.JTextField();
        txtLimiteDiarioSaque = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        pnlListagem = new javax.swing.JPanel();
        lblContas = new javax.swing.JLabel();
        scrContas = new javax.swing.JScrollPane();
        lstContas = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        bntExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        bntRestaurarLixeira = new javax.swing.JButton();
        bntExcluirLixeira = new javax.swing.JButton();
        bntEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton2.setText("Restaurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Conta");

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("Número:");

        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("Saldo:");

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("Status:");

        lblDataCriacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataCriacao.setText("Data de Criação:");

        lblLimiteDiarioSaque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLimiteDiarioSaque.setText("Limite Diário de Saque:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Seja Bem-Vindo!");

        javax.swing.GroupLayout pnlCadastroContaLayout = new javax.swing.GroupLayout(pnlCadastroConta);
        pnlCadastroConta.setLayout(pnlCadastroContaLayout);
        pnlCadastroContaLayout.setHorizontalGroup(
            pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvar)
                            .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDataCriacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLimiteDiarioSaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumero)
                                    .addComponent(txtSaldo)
                                    .addComponent(txtStatus)
                                    .addComponent(txtDataCriacao)
                                    .addComponent(txtLimiteDiarioSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlCadastroContaLayout.setVerticalGroup(
            pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldo)
                    .addComponent(txtSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataCriacao)
                    .addComponent(txtDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteDiarioSaque)
                    .addComponent(txtLimiteDiarioSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnSalvar))
        );

        tabPrincipal.addTab("Cadastrar Conta", pnlCadastroConta);

        lblContas.setText("Contas:");

        scrContas.setViewportView(lstContas);

        radNaoExcluidos.setText("Não excluídos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });

        radExcluidos.setText("Excluídos");
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setText("Lixeira:");

        bntRestaurarLixeira.setText("Restaurar");

        bntExcluirLixeira.setText("Excluir");

        bntEsvaziarLixeira.setText("Esvaziar");

        lblAlerta.setBackground(new java.awt.Color(255, 153, 153));
        lblAlerta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione uma conta!");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(lblContas)
                        .addGap(103, 103, 103)
                        .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrContas, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(lblLixeira)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlListagemLayout.createSequentialGroup()
                                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radNaoExcluidos)
                                    .addComponent(radExcluidos))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlListagemLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(bntExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(371, 371, 371))))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContas)
                    .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntRestaurarLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluirLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntEsvaziarLixeira))
                    .addComponent(scrContas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        
        double numero = Double.parseDouble (txtNumero.getText());
        double saldo = Double.parseDouble (txtSaldo.getText());
        String status = txtStatus.getText();
        LocalDate dataCriacao = LocalDate.parse(txtDataCriacao.getText());
        double limiteDiariSaque = Double.parseDouble (txtLimiteDiarioSaque.getText());
        
        //JOptionPane.showMessageDialog(this,"Conta Cadastrada com Sucesso");
        JOptionPane.showMessageDialog(this, "Conta Cadastrada!" + "\n"
                                            + "Numero: "+ numero + "\n" 
                                            + "Saldo: " + saldo + "\n" 
                                            + "Status: " + status + "\n" 
                                            + "Data Criação: " + dataCriacao + "\n" 
                                            + "Limite Diário de Saque:" + limiteDiariSaque);
         
        Conta c1 = new Conta();
        ContaRepository CRepository = new ContaRepository();
        
        c1.setNumero(numero);
        c1.setSaldo(saldo);
        c1.setStatus(status);
        c1.setDataCriacao(dataCriacao);
        c1.setLimiteDiariSaque (limiteDiariSaque);
        
        new ContaRepository().saveOrUpdate(c1);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed
        // TODO add your handling code here:
        //if (evt.getStateChange() = )
    }//GEN-LAST:event_radExcluidosActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNovaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsvaziarLixeira;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExcluirLixeira;
    private javax.swing.JButton bntRestaurarLixeira;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblLimiteDiarioSaque;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstContas;
    private javax.swing.JPanel pnlCadastroConta;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrContas;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtDataCriacao;
    private javax.swing.JTextField txtLimiteDiarioSaque;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
