/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Emprestimo.Emprestimo;
import io.github.nicolazlxl.TesteSQLPOO.Emprestimo.EmprestimoRepository;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.Font;

/**
 *
 * @author Dell
 */
public class CadastrarNovoEmprestimo extends javax.swing.JFrame {
    private final EmprestimoRepository repository;
    private final DefaultListModel<Emprestimo> modelEmprestimo;
    /**
     * Creates new form CadastrarNovoEmprestimo
     */
    public CadastrarNovoEmprestimo() {
        repository = new EmprestimoRepository();
        
        modelEmprestimo = new DefaultListModel<>();
        modelEmprestimo.addAll(repository.findAll());
        initComponents();

        lblAlerta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroEmprestimo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblValorTotalEmprestimo = new javax.swing.JLabel();
        lblTaxaJuros = new javax.swing.JLabel();
        lblNumeroParcelas = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtValorEmprestimo = new javax.swing.JTextField();
        txtTaxaJuros = new javax.swing.JTextField();
        txtNumeroParcelas = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        pnlListagem = new javax.swing.JPanel();
        lblListagemEmprestimo = new javax.swing.JLabel();
        scrEmprestimo = new javax.swing.JScrollPane();
        lstEmprestimo = new javax.swing.JList<>();
        radPresenteBancoEmprestimo = new javax.swing.JRadioButton();
        radExcluidoEmprestimo = new javax.swing.JRadioButton();
        btnExcluirEmprestimo = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 0, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Vamos fazer um Emprestimo?");

        lblValorTotalEmprestimo.setText("Valor Total do Emprestimo:");

        lblTaxaJuros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTaxaJuros.setText("Taxa de Juros:");

        lblNumeroParcelas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeroParcelas.setText("Numero de Parcelas:");

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("Status:");

        btnSalvar.setBackground(new java.awt.Color(51, 0, 51));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroEmprestimoLayout = new javax.swing.GroupLayout(pnlCadastroEmprestimo);
        pnlCadastroEmprestimo.setLayout(pnlCadastroEmprestimoLayout);
        pnlCadastroEmprestimoLayout.setHorizontalGroup(
            pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroEmprestimoLayout.createSequentialGroup()
                .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroEmprestimoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(pnlCadastroEmprestimoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumeroParcelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTaxaJuros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValorTotalEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorEmprestimo)
                            .addComponent(txtTaxaJuros)
                            .addComponent(txtNumeroParcelas)
                            .addComponent(txtStatus)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroEmprestimoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        pnlCadastroEmprestimoLayout.setVerticalGroup(
            pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroEmprestimoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotalEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Cadastrar Emprestimo", pnlCadastroEmprestimo);

        lblListagemEmprestimo.setText("Listagem de Emprestimos:");

        lstEmprestimo.setModel(modelEmprestimo);
        scrEmprestimo.setViewportView(lstEmprestimo);

        buttonGroup1.add(radPresenteBancoEmprestimo);
        radPresenteBancoEmprestimo.setText("Presente no Banco");
        radPresenteBancoEmprestimo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radPresenteBancoEmprestimoItemStateChanged(evt);
            }
        });
        radPresenteBancoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPresenteBancoEmprestimoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radExcluidoEmprestimo);
        radExcluidoEmprestimo.setText("Excluidos");
        radExcluidoEmprestimo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidoEmprestimoItemStateChanged(evt);
            }
        });
        radExcluidoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidoEmprestimoActionPerformed(evt);
            }
        });

        btnExcluirEmprestimo.setBackground(new java.awt.Color(51, 0, 51));
        btnExcluirEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirEmprestimo.setText("Excluir");
        btnExcluirEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEmprestimoActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLixeira.setText("Lixeira:");

        btnRestaurar.setBackground(new java.awt.Color(51, 0, 51));
        btnRestaurar.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        btnExcluirLixeira.setBackground(new java.awt.Color(51, 0, 51));
        btnExcluirLixeira.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirLixeira.setText("Excluir");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnEsvaziarLixeira.setBackground(new java.awt.Color(51, 0, 51));
        btnEsvaziarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        btnEsvaziarLixeira.setText("Esvaziar");
        btnEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setBackground(new java.awt.Color(255, 102, 204));
        lblAlerta.setForeground(new java.awt.Color(0, 0, 0));
        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione um Emprestimo");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(scrEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radPresenteBancoEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(radExcluidoEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluirEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEsvaziarLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblListagemEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListagemEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radPresenteBancoEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidoEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirEmprestimo)
                        .addGap(28, 28, 28)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEsvaziarLixeira))
                    .addComponent(scrEmprestimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlerta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        double valorTotal;
        double taxaJuros;
        int numeroParcelas;

        try {
            valorTotal = Double.parseDouble(txtValorEmprestimo.getText());
            taxaJuros = Double.parseDouble(txtTaxaJuros.getText());
            numeroParcelas = Integer.parseInt(txtNumeroParcelas.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Por favor, insira valores numéricos válidos para valor, juros e parcelas.",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (valorTotal <= 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "O valor do empréstimo deve ser maior que zero.",
                    "Valor Inválido",
                    JOptionPane.WARNING_MESSAGE);
            return; 
        }

        if (numeroParcelas <= 0 || numeroParcelas > 420) {
            JOptionPane.showMessageDialog(
                    this,
                    "O número de parcelas deve ser entre 1 e 420.",
                    "Parcelas Inválidas",
                    JOptionPane.WARNING_MESSAGE);
            return; 
        }

        if (taxaJuros < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "A taxa de juros não pode ser negativa.",
                    "Taxa Inválida",
                    JOptionPane.WARNING_MESSAGE);
            return; 
        }

        String status = txtStatus.getText();

        Emprestimo e1 = new Emprestimo();
        EmprestimoRepository e1Repository = new EmprestimoRepository();

        e1.setValorTotal(valorTotal);
        e1.setNumeroParcelas(numeroParcelas);
        e1.setTaxaJuros(taxaJuros);
        e1.setStatus(status);

        e1Repository.saveOrUpdate(e1);

        JOptionPane.showMessageDialog(
                this,
                "Empréstimo salvo com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);


        txtValorEmprestimo.setText("");
        txtTaxaJuros.setText("");
        txtNumeroParcelas.setText("");
        txtStatus.setText("");

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radPresenteBancoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPresenteBancoEmprestimoActionPerformed
        enableTrash(false);
            
            modelEmprestimo.clear();
            modelEmprestimo.addAll(repository.findAll());
    }//GEN-LAST:event_radPresenteBancoEmprestimoActionPerformed

    private void radPresenteBancoEmprestimoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radPresenteBancoEmprestimoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radPresenteBancoEmprestimoItemStateChanged

    private void radExcluidoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidoEmprestimoActionPerformed
        enableTrash(true);
           
            modelEmprestimo.clear();
            modelEmprestimo.addAll(repository.findTrash());
    }//GEN-LAST:event_radExcluidoEmprestimoActionPerformed

    private void radExcluidoEmprestimoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidoEmprestimoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radExcluidoEmprestimoItemStateChanged

    private void btnExcluirEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEmprestimoActionPerformed
        if(lstEmprestimo.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um Contrato");
            return;
        }
        if(lstEmprestimo.getSelectedIndices().length == 1){
             List<Emprestimo> selection = lstEmprestimo.getSelectedValuesList();
             Emprestimo selecionada = selection.getFirst();
             selecionada.setToTrash(true);
             repository.saveOrUpdate(selecionada);
            modelEmprestimo.removeElement(selecionada);
        }else{
            List<Emprestimo> selection = lstEmprestimo.getSelectedValuesList();
            for(Emprestimo aux: selection){ 
                aux.setToTrash(true);
             repository.saveOrUpdate(aux);
                modelEmprestimo.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirEmprestimoActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if(lstEmprestimo.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um Emprestimo");
            return;
        }
        if(lstEmprestimo.getSelectedIndices().length == 1){
             List<Emprestimo> selection = lstEmprestimo.getSelectedValuesList();
             Emprestimo selecionada = selection.getFirst();
             selecionada.setToTrash(false);
             repository.saveOrUpdate(selecionada);
            modelEmprestimo.removeElement(selecionada);
            
            
        }else{
            List<Emprestimo> selection = lstEmprestimo.getSelectedValuesList();
            
            for(Emprestimo  aux: selection){
                aux.setToTrash(false);
             repository.saveOrUpdate(aux);
                modelEmprestimo.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarLixeiraActionPerformed
        repository.EmptyTrash();
         modelEmprestimo.clear();
         showWarning("Lixeira esvaziada");
    }//GEN-LAST:event_btnEsvaziarLixeiraActionPerformed

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
        if(lstEmprestimo.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um Emprestimo");
            return;
        }
        if(lstEmprestimo.getSelectedIndices().length == 1){
             List<Emprestimo> selection = lstEmprestimo.getSelectedValuesList();
             Emprestimo selecionada = selection.getFirst();
             repository.delete(selecionada);
            modelEmprestimo.removeElement(selecionada);
             showWarning("Emprestimo deletada");
            
        }else{
            List<Emprestimo> selection = lstEmprestimo.getSelectedValuesList();
            for(Emprestimo aux: selection){
              showWarning("Emprestimo deletadas");
                repository.delete(aux);
                modelEmprestimo.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarNovoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarNovoEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziarLixeira;
    private javax.swing.JButton btnExcluirEmprestimo;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblListagemEmprestimo;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblNumeroParcelas;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTaxaJuros;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorTotalEmprestimo;
    private javax.swing.JList<Emprestimo> lstEmprestimo;
    private javax.swing.JPanel pnlCadastroEmprestimo;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidoEmprestimo;
    private javax.swing.JRadioButton radPresenteBancoEmprestimo;
    private javax.swing.JScrollPane scrEmprestimo;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtNumeroParcelas;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTaxaJuros;
    private javax.swing.JTextField txtValorEmprestimo;
    // End of variables declaration//GEN-END:variables

    private void enableTrash(boolean status) {
          btnExcluirEmprestimo.setEnabled(!status);
          
          btnExcluirLixeira.setEnabled(status);
          btnEsvaziarLixeira.setEnabled(status);
          btnRestaurar.setEnabled(status);
    }

    private void showWarning(String warning) {
        lblAlerta.setText(warning);
          lblAlerta.setVisible(true);
          
          Timer timer = new Timer(4000, (e) -> {
              lblAlerta.setVisible(false);
              ((Timer) e.getSource()).stop();
          });
          
          timer.setRepeats(false);
          timer.start();
    }
    
    
}
