/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.nicolazlxl.TesteSQLPOO.gui;

import io.github.nicolazlxl.TesteSQLPOO.Conta.Conta;
import io.github.nicolazlxl.TesteSQLPOO.Conta.ContaRepository;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author taina
 */
public class CadastroNovaConta extends javax.swing.JFrame {
    
    private final DefaultListModel<Conta> modelConta;
    private final ContaRepository repository;

    /**
     * Creates new form CadastroNovaConta
     */
    public CadastroNovaConta() {
        
        repository = new ContaRepository();
        
        modelConta = new DefaultListModel<>();
        modelConta.addAll(repository.findAll());
        initComponents();
        
        lblAlerta.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastroConta = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        lblLimiteDiarioSaque = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtDataCriacao = new javax.swing.JTextField();
        txtLimiteDiarioSaque = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cmbStatusConta = new javax.swing.JComboBox<>();
        pnlListagem = new javax.swing.JPanel();
        lblContas = new javax.swing.JLabel();
        scrContas = new javax.swing.JScrollPane();
        lstContas = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        bntExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        bntRestaurarLixeira = new javax.swing.JButton();
        bntExcluirLixeira = new javax.swing.JButton();
        bntEsvaziarLixeira = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton2.setText("Restaurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Conta");

        tabPrincipal.setBackground(new java.awt.Color(221, 255, 221));
        tabPrincipal.setForeground(new java.awt.Color(0, 102, 51));

        pnlCadastroConta.setBackground(new java.awt.Color(221, 255, 221));
        pnlCadastroConta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 51)));

        lblNumero.setForeground(new java.awt.Color(0, 102, 51));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("Número:");

        lblSaldo.setForeground(new java.awt.Color(0, 102, 51));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("Saldo:");

        lblStatus.setForeground(new java.awt.Color(0, 102, 51));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("Status:");

        lblDataCriacao.setForeground(new java.awt.Color(0, 102, 51));
        lblDataCriacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataCriacao.setText("Data de Criação:");

        lblLimiteDiarioSaque.setForeground(new java.awt.Color(0, 102, 51));
        lblLimiteDiarioSaque.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLimiteDiarioSaque.setText("Limite Diário de Saque:");

        btnSalvar.setBackground(new java.awt.Color(0, 102, 51));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblTitulo.setBackground(new java.awt.Color(0, 102, 51));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastre uma nova Conta:");
        lblTitulo.setOpaque(true);

        cmbStatusConta.setForeground(new java.awt.Color(0, 102, 51));
        cmbStatusConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativa", "Inativa" }));

        javax.swing.GroupLayout pnlCadastroContaLayout = new javax.swing.GroupLayout(pnlCadastroConta);
        pnlCadastroConta.setLayout(pnlCadastroContaLayout);
        pnlCadastroContaLayout.setHorizontalGroup(
            pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLimiteDiarioSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDataCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSaldo)
                            .addComponent(txtDataCriacao)
                            .addComponent(txtLimiteDiarioSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtNumero)
                            .addComponent(cmbStatusConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlCadastroContaLayout.setVerticalGroup(
            pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroContaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo))
                .addGap(10, 10, 10)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatusConta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataCriacao))
                .addGap(12, 12, 12)
                .addGroup(pnlCadastroContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLimiteDiarioSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimiteDiarioSaque))
                .addGap(31, 31, 31)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPrincipal.addTab("Cadastrar Conta", pnlCadastroConta);

        pnlListagem.setBackground(new java.awt.Color(221, 255, 221));
        pnlListagem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 51)));

        lblContas.setBackground(new java.awt.Color(0, 102, 51));
        lblContas.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblContas.setForeground(new java.awt.Color(0, 102, 51));
        lblContas.setText("Contas:");

        lstContas.setModel(modelConta);
        scrContas.setViewportView(lstContas);

        buttonGroup1.add(radNaoExcluidos);
        radNaoExcluidos.setForeground(new java.awt.Color(0, 102, 51));
        radNaoExcluidos.setText("Não excluídos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        buttonGroup1.add(radExcluidos);
        radExcluidos.setForeground(new java.awt.Color(0, 102, 51));
        radExcluidos.setText("Excluídos");
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        bntExcluir.setBackground(new java.awt.Color(0, 102, 51));
        bntExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLixeira.setForeground(new java.awt.Color(0, 102, 51));
        lblLixeira.setText("Lixeira:");

        bntRestaurarLixeira.setBackground(new java.awt.Color(0, 102, 51));
        bntRestaurarLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntRestaurarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntRestaurarLixeira.setText("Restaurar");
        bntRestaurarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestaurarLixeiraActionPerformed(evt);
            }
        });

        bntExcluirLixeira.setBackground(new java.awt.Color(0, 102, 51));
        bntExcluirLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntExcluirLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluirLixeira.setText("Excluir");
        bntExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirLixeiraActionPerformed(evt);
            }
        });

        bntEsvaziarLixeira.setBackground(new java.awt.Color(0, 102, 51));
        bntEsvaziarLixeira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntEsvaziarLixeira.setForeground(new java.awt.Color(255, 255, 255));
        bntEsvaziarLixeira.setText("Esvaziar");
        bntEsvaziarLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEsvaziarLixeiraActionPerformed(evt);
            }
        });

        lblAlerta.setBackground(new java.awt.Color(0, 204, 51));
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 255, 255));
        lblAlerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlerta.setText("Selecione uma conta!");
        lblAlerta.setOpaque(true);

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(scrContas, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLixeira)
                                    .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(pnlListagemLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radNaoExcluidos)
                                    .addComponent(bntExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlListagemLayout.createSequentialGroup()
                                        .addComponent(radExcluidos)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(365, 365, 365))
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(lblContas)
                        .addGap(701, 701, 701))))
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblContas)
                .addGap(15, 15, 15)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radExcluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntRestaurarLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluirLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntEsvaziarLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrContas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        String numero = txtNumero.getText();
        
        if (numero.length() != 5) {
            JOptionPane.showMessageDialog(this, "O número da conta deve ter 5 caracteres.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        double saldo;
        try {
            saldo = Double.parseDouble(txtSaldo.getText());
            if (saldo <= 0) {
                JOptionPane.showMessageDialog(this, "O saldo deve ser positivo.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O valor deve ser um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        String status = (String) cmbStatusConta.getSelectedItem(); 
        
        LocalDate dataCriacao;
        
        try {
            dataCriacao = LocalDate.parse(txtDataCriacao.getText());
        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Use o formato AAAA-MM-DD.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        double limiteDiariSaque; 

        try {
        limiteDiariSaque = Double.parseDouble(txtLimiteDiarioSaque.getText());
        if (limiteDiariSaque <= 0) {
            JOptionPane.showMessageDialog(this, "O limite de saque deve ser um valor maior que zero.", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Digite um valor numérico válido para o limite de saque.","Formato Inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Conta Cadastrada com Sucesso!" + "\n"
                                            + "Numero: "+ numero + "\n" 
                                            + "Saldo: " + saldo + "\n" 
                                            + "Status: " + status + "\n" 
                                            + "Data Criação: " + dataCriacao + "\n" 
                                            + "Limite Diário de Saque:" + limiteDiariSaque);
         
        Conta c1 = new Conta();
        
        c1.setNumero(numero);
        c1.setSaldo(saldo);
        c1.setStatus(status);
        c1.setDataCriacao(dataCriacao);
        c1.setLimiteDiariSaque (limiteDiariSaque);
        
        repository.saveOrUpdate(c1);
        modelConta.addElement(c1);

        txtNumero.setText("");
        txtSaldo.setText("");
        cmbStatusConta.setSelectedIndex(-1);
        txtDataCriacao.setText("");
        txtLimiteDiarioSaque.setText("");
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed

        enableTrash(true);
        modelConta.clear();
        modelConta.addAll(repository.findTrash());
        
    }//GEN-LAST:event_radExcluidosActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed

        if(lstContas.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma conta!");
            return;
        }
      
        List<Conta> selection = lstContas.getSelectedValuesList();
            
        for(Conta aux: selection){
                
            aux.setToTrash(true);
          
            repository.saveOrUpdate(aux);
            modelConta.removeElement(aux);      
        }  
        
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed

        enableTrash(false);
        modelConta.clear();
        modelConta.addAll(repository.findAll());
        
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    private void bntRestaurarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestaurarLixeiraActionPerformed
      
        if(lstContas.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma conta!");
            return;
        }
     
        List<Conta> selection = lstContas.getSelectedValuesList();
            
        for(Conta aux: selection){
                
            aux.setToTrash(false);
          
            repository.saveOrUpdate(aux);
            modelConta.removeElement(aux);      
        }
        
    }//GEN-LAST:event_bntRestaurarLixeiraActionPerformed

    private void bntExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirLixeiraActionPerformed
 
        if(lstContas.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos uma conta!");
            return;
        }
     
        List<Conta> selection = lstContas.getSelectedValuesList();
            
        for(Conta aux: selection){
            repository.delete(aux);
            modelConta.removeElement(aux);
            showWarning("Conta Excluída!");
        }
        
    }//GEN-LAST:event_bntExcluirLixeiraActionPerformed

    private void bntEsvaziarLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEsvaziarLixeiraActionPerformed

        repository.EmptyTrash();
        modelConta.clear();
        showWarning("Lixeira esvaziada");
        
    }//GEN-LAST:event_bntEsvaziarLixeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroNovaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroNovaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsvaziarLixeira;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExcluirLixeira;
    private javax.swing.JButton bntRestaurarLixeira;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbStatusConta;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblLimiteDiarioSaque;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Conta> lstContas;
    private javax.swing.JPanel pnlCadastroConta;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrContas;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtDataCriacao;
    private javax.swing.JTextField txtLimiteDiarioSaque;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables

    private void enableTrash(boolean status) {
    
        bntExcluir.setEnabled(!status);

        bntExcluirLixeira.setEnabled(status);
        bntRestaurarLixeira.setEnabled(status);
        bntEsvaziarLixeira.setEnabled(status);
    }
    
    private void showWarning(String warning) {
            
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
          
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
          
        timer.setRepeats(false);
        timer.start();
    }
    
}
